nebula:
  userName: root
  password: nebula
  hostAddresses[0]: ip:9669
  minConnsSize: 5
  maxConnSize: 10
  timeout: 300000
  idleTime: 180000

path:
  uploadFilePath: /opt/project/java/graphFile
  #  uploadFilePath: D:/data/graphFile
  importerPath: /data1/opt
#  importerPath: D:/data